-- V10: 면접 세션 도메인 (C2 — 면접 대비 가치 계획 §3.3·§4.1)
--
-- 면접 세션: 승급된 개념의 면접 질문에 대해 설명 인출을 검증하는, 일반 세션과 별개의 회원 전용 세션.
-- 면접 준비도: 개념별 설명 검증 상태(사용자 소유, 기존 숙련도와 독립된 축 — DI4).
-- [프로토타입 범위 축소] 계획 초안의 started_at/completed_at 컬럼은 이번 단계(C2)에서 쓰이는 지표가 없어 생략한다.
-- 지표 확장(C5)에서 필요해지면 그때 별도 마이그레이션으로 추가한다.
create table interview_session (
    id bigint generated by default as identity,
    user_id bigint not null,
    session_date date not null,
    status varchar(255) not null
        constraint interview_session_status_check
        check (status in ('IN_PROGRESS', 'COMPLETED')),
    -- 낙관적 락(Session.version과 같은 관례) — 동시 제출이 같은 칸을 두 번 전진시키는 것을 막는다.
    version bigint not null default 0,
    primary key (id)
);

create index idx_interview_session_user_date on interview_session (user_id, session_date);

-- 세션에 배정된 면접 질문 칸(@ElementCollection). judged=true인 칸이 하나 이상 있어야 그 세션이 하루 쿼터에 반영된다(전량 폴백은 미차감).
-- satisfied_points_raw: 그 질문의 루브릭 포인트 순서에 맞춘 "1,0,1" 형태의 충족 여부 직렬화(계획 §4.1 "구현 판단"에 따른 선택).
create table interview_session_item (
    item_index integer not null,
    session_id bigint not null,
    position integer not null,
    prompt_id bigint not null,
    submitted_text text,
    judged boolean not null default false,
    satisfied_points_raw varchar(255),
    judge_comment text,
    judged_at timestamp(6) with time zone,
    primary key (item_index, session_id)
);

alter table interview_session_item
    add constraint fk_interview_session_item_session
    foreign key (session_id)
    references interview_session;

alter table interview_session_item
    add constraint fk_interview_session_item_prompt
    foreign key (prompt_id)
    references interview_prompt;

-- 면접 준비도(사용자·개념별 1행). 채점 성공(judged=true) 시에만 갱신된다 — 폴백은 준비도를 바꾸지 않는다.
create table interview_readiness (
    id bigint generated by default as identity,
    user_id bigint not null,
    concept_id bigint not null,
    status varchar(255) not null
        constraint interview_readiness_status_check
        check (status in ('UNVERIFIED', 'PARTIAL', 'VERIFIED')),
    satisfied_count integer not null,
    total_count integer not null,
    updated_at timestamp(6) with time zone not null,
    primary key (id),
    constraint uk_interview_readiness unique (user_id, concept_id)
);

alter table interview_readiness
    add constraint fk_interview_readiness_concept
    foreign key (concept_id)
    references concept;
