-- V1: 스키마 베이스라인 (2026-07-18)
--
-- 이 시점의 JPA 엔티티 매핑에서 Hibernate(PostgreSQLDialect) 스키마 내보내기로 생성한 뒤,
-- 제약에 명시적 이름을 부여해 정리했다(무작위 해시 이름 금지 — 이후 마이그레이션이 참조할 수 있게).
-- 이후 모든 스키마 변경은 ddl-auto가 아니라 새 V마이그레이션 파일로만 수행한다(ddl-auto는 validate 전용).
-- 체크 제약 이름은 PostgreSQL 기본 규칙(<table>_<column>_check)을 따른다.

create table concept (
    id bigint generated by default as identity,
    category varchar(255) constraint concept_category_check check (category in ('DATA_STRUCTURE','ALGORITHM','OPERATING_SYSTEM','NETWORK','DATABASE','COMPUTER_ARCHITECTURE','SOFTWARE_ENGINEERING','SECURITY')),
    description text,
    name varchar(255) not null,
    primary key (id),
    constraint uk_concept_name unique (name)
);

create table concept_mastery (
    level integer not null,
    next_review_date date not null,
    concept_id bigint not null,
    id bigint generated by default as identity,
    last_problem_id bigint not null,
    user_id bigint not null,
    primary key (id),
    constraint uk_concept_mastery_user_concept unique (user_id, concept_id)
);

create table content_report (
    created_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    problem_id bigint not null,
    user_id bigint not null,
    category varchar(255) not null constraint content_report_category_check check (category in ('WRONG_ANSWER','QUESTION_ERROR','HINT_ERROR','OTHER')),
    message text,
    primary key (id)
);

create table extra_study (
    open_misconception_hint_seen boolean,
    open_revealed boolean,
    open_revealed_hint_count integer,
    open_wrong_attempt_count integer,
    id bigint generated by default as identity,
    open_problem_id bigint,
    user_id bigint not null,
    version bigint not null,
    open_submitted_answer text,
    primary key (id),
    constraint uk_extra_study_user unique (user_id)
);

create table extra_study_solved (
    extra_study_id bigint not null,
    problem_id bigint not null,
    primary key (extra_study_id, problem_id)
);

create table misconception_hint (
    id bigint generated by default as identity,
    problem_id bigint,
    message text not null,
    primary key (id)
);

create table misconception_hint_expected_answer (
    misconception_hint_id bigint not null,
    answer varchar(255) not null,
    primary key (misconception_hint_id, answer)
);

create table problem (
    enrichment_id bigint,
    id bigint generated by default as identity,
    code_snippet text,
    difficulty varchar(255) constraint problem_difficulty_check check (difficulty in ('EASY','MEDIUM','HARD')),
    explanation text,
    problem_type varchar(255) constraint problem_problem_type_check check (problem_type in ('DEFINITION_RECALL','DERIVATION')),
    question_text text not null,
    representative_answer varchar(255) not null,
    primary key (id),
    constraint uk_problem_enrichment_id unique (enrichment_id)
);

create table problem_acceptable_answer (
    problem_id bigint not null,
    answer varchar(255) not null,
    primary key (problem_id, answer)
);

create table problem_concept (
    concept_index integer not null,
    concept_id bigint not null,
    problem_id bigint not null,
    primary key (concept_index, problem_id)
);

create table problem_enrichment (
    id bigint generated by default as identity,
    body text not null,
    quote text,
    title text not null,
    primary key (id)
);

create table problem_enrichment_item (
    item_index integer not null,
    enrichment_id bigint not null,
    item_description text not null,
    item_title text not null,
    primary key (item_index, enrichment_id)
);

create table problem_hint (
    hint_index integer not null,
    problem_id bigint not null,
    hint_code_snippet text,
    hint_text text not null,
    primary key (hint_index, problem_id)
);

create table scrap (
    created_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    problem_id bigint not null,
    user_id bigint not null,
    primary key (id),
    constraint uk_scrap_user_problem unique (user_id, problem_id)
);

create table study_session (
    session_date date not null,
    id bigint generated by default as identity,
    user_id bigint not null,
    version bigint not null,
    status varchar(255) not null constraint study_session_status_check check (status in ('IN_PROGRESS','COMPLETED')),
    primary key (id),
    constraint uk_study_session_user_date unique (user_id, session_date)
);

create table study_session_item (
    item_index integer not null,
    misconception_hint_seen boolean not null,
    position integer not null,
    revealed boolean not null,
    revealed_hint_count integer not null,
    solved boolean not null,
    wrong_attempt_count integer not null,
    problem_id bigint not null,
    session_id bigint not null,
    submitted_answer text,
    primary key (item_index, session_id)
);

create table users (
    daily_session_size integer not null,
    last_study_date date,
    streak_count integer not null,
    id bigint generated by default as identity,
    email varchar(255),
    password_hash varchar(255),
    role varchar(255) not null constraint users_role_check check (role in ('GUEST','MEMBER')),
    primary key (id),
    constraint uk_users_email unique (email)
);

alter table extra_study_solved
    add constraint fk_extra_study_solved_extra_study
    foreign key (extra_study_id)
    references extra_study;

alter table misconception_hint
    add constraint fk_misconception_hint_problem
    foreign key (problem_id)
    references problem;

alter table misconception_hint_expected_answer
    add constraint fk_misconception_hint_expected_answer_hint
    foreign key (misconception_hint_id)
    references misconception_hint;

alter table problem
    add constraint fk_problem_enrichment
    foreign key (enrichment_id)
    references problem_enrichment;

alter table problem_acceptable_answer
    add constraint fk_problem_acceptable_answer_problem
    foreign key (problem_id)
    references problem;

alter table problem_concept
    add constraint fk_problem_concept_concept
    foreign key (concept_id)
    references concept;

alter table problem_concept
    add constraint fk_problem_concept_problem
    foreign key (problem_id)
    references problem;

alter table problem_enrichment_item
    add constraint fk_problem_enrichment_item_enrichment
    foreign key (enrichment_id)
    references problem_enrichment;

alter table problem_hint
    add constraint fk_problem_hint_problem
    foreign key (problem_id)
    references problem;

alter table study_session_item
    add constraint fk_study_session_item_session
    foreign key (session_id)
    references study_session;
