-- V3: 문제 승인 상태 도입 + 승인 전이 감사 로그 (콘텐츠 파이프라인 Phase 1)
--
-- approval_status는 NOT NULL이므로 기존 행이 있는 DB에서도 적용되도록 default를 거쳐 추가한다.
-- 초안(DRAFT)이 기본이라 마이그레이션 직후 기존 행은 서빙에서 빠진다 — 운영 유입은 관리자 검수 경로만
-- 존재하므로 의도된 동작이고, 로컬·테스트 시드는 로더가 APPROVED로 직접 넣는다.
alter table problem add column approval_status varchar(255) default 'DRAFT' not null
    constraint problem_approval_status_check check (approval_status in ('DRAFT','IN_REVIEW','APPROVED','REJECTED','RETRACTED'));
alter table problem alter column approval_status drop default;

create table problem_approval_log (
    id bigint generated by default as identity,
    problem_id bigint not null,
    from_status varchar(255) not null,
    to_status varchar(255) not null,
    reason text,
    actor_user_id bigint not null,
    created_at timestamp(6) with time zone not null,
    primary key (id)
);

alter table problem_approval_log
    add constraint fk_problem_approval_log_problem
    foreign key (problem_id)
    references problem;
