-- V9: 면접 질문 콘텐츠 도메인 (C1 — 면접 대비 가치 계획 §3.3·§4.1)
--
-- 개념에 귀속되는 큐레이션 콘텐츠: 질문 문구 + 모범 설명 + 루브릭(핵심 포인트 목록, 순서 보존).
-- 승인 상태는 문제와 같은 모델(DRAFT/IN_REVIEW/APPROVED/REJECTED/RETRACTED)을 재사용한다 — APPROVED만 서빙된다.
-- 타입·제약은 V1 baseline 관례를 따른다: approval_status는 varchar(255)+in-list 체크(ddl-auto=validate가 Hibernate의
-- @Enumerated(STRING) 기본 매핑 varchar(255)와 일치해야 함, V7 주석 참고). 개념 1 — 0..N 면접 질문.
create table interview_prompt (
    id bigint generated by default as identity,
    concept_id bigint not null,
    question text not null,
    model_answer text not null,
    approval_status varchar(255) not null
        constraint interview_prompt_approval_status_check
        check (approval_status in ('DRAFT','IN_REVIEW','APPROVED','REJECTED','RETRACTED')),
    primary key (id)
);

-- 루브릭 핵심 포인트(@ElementCollection·@OrderColumn). position으로 순서를 보존한다(problem_hint 관례와 동일 구조).
create table interview_prompt_rubric_point (
    position integer not null,
    prompt_id bigint not null,
    point_text text not null,
    primary key (position, prompt_id)
);

alter table interview_prompt
    add constraint fk_interview_prompt_concept
    foreign key (concept_id)
    references concept;

alter table interview_prompt_rubric_point
    add constraint fk_interview_prompt_rubric_point_prompt
    foreign key (prompt_id)
    references interview_prompt;
